// Per-project .claudable/ARCHITECTURE.md generator (how this project runs in the preview).
import path from 'path';
import fs from 'fs/promises';
import { stackKind } from '@/lib/config/stacks';

/**
 * Write a per-project `.claudable/ARCHITECTURE.md` describing how THIS project
 * runs in the preview (stack, isolation, containers, ports, deploy). Regenerated
 * on each preview start; the agent can read it, and it documents the setup for
 * whoever opens the project. Best-effort — never blocks the preview.
 */
export async function writeArchitectureSummary(opts: {
  projectPath: string; projectName: string; templateType: string | null | undefined;
  isStatic: boolean; frontendContainer: string | null; backendContainer: string | null;
  backendInProcess: boolean; proxy?: string[]; port: number; url: string;
  dbUrl: string | null; sandboxNet?: string;
}): Promise<void> {
  try {
    const { projectPath, projectName, templateType, isStatic, frontendContainer,
      backendContainer, backendInProcess, proxy, port, url, dbUrl, sandboxNet } = opts;
    const kind = stackKind(templateType);
    const isolated = !!frontendContainer || !!backendContainer;
    const net = sandboxNet ? ` on the egress-locked \`${sandboxNet}\` network` : '';
    const L: string[] = [];
    L.push(`# ${projectName} — Architecture`, '');
    L.push('> Auto-generated by Claudable on preview start. How this project runs in the preview.', '');
    L.push(`- **Stack:** ${isStatic ? 'static site (imported existing repo)' : (templateType || kind)}`);
    L.push(`- **Preview URL:** ${url}`);
    L.push(`- **Preview port:** ${port}`);
    if (dbUrl) L.push('- **Database:** a provisioned Postgres (its `DATABASE_URL` is injected at runtime)');
    L.push('', '## Runtime');
    if (isStatic) {
      L.push(`- **Frontend:** static files served by Claudable's built-in file server.`);
      if (backendContainer) L.push(`- **Backend:** isolated container \`${backendContainer}\`, built from the project's own Dockerfile — non-root, \`cap-drop ALL\`, no-new-privileges, memory/CPU/PID limits${net}.`);
      else if (backendInProcess) L.push('- **Backend:** runs in Claudable\'s process (not isolated).');
      if (proxy?.length) L.push(`- **Proxy:** \`${proxy.join('`, `')}\` are forwarded to the backend.`);
    } else if (frontendContainer && kind === 'laravel') {
      L.push(`- **Runtime:** NewStory Filament CMS (Laravel + Filament v4, PHP 8.3) in isolated container \`${frontendContainer}\` — the app lives under \`src/\`, served by \`php artisan serve\` (PHP interpreted per request; PHP edits are immediate, asset changes need a vite rebuild). First start composer-installs the template and builds assets; the DB is a managed **Postgres** if attached, else file **SQLite** (\`src/database/database.sqlite\`). Non-root, \`cap-drop ALL\`, no-new-privileges, resource limits${net}.`);
      L.push('- **Admin panel:** available at `/admin` (Filament).');
    } else if (frontendContainer) {
      L.push(`- **Dev server:** isolated container \`${frontendContainer}\` — bind-mounts **only this project's source**, non-root, \`cap-drop ALL\`, no-new-privileges, memory/CPU/PID limits${net}.`);
    } else {
      L.push(`- **Dev server:** ${kind} dev server running in Claudable's process (not isolated).`);
    }
    L.push('', '## Isolation');
    L.push(isolated
      ? 'This project\'s running code is confined to a hardened container: non-root, all Linux capabilities dropped, no privilege escalation, resource limits, no host mounts beyond its own source, and an egress-locked network (public internet allowed; the box\'s private network — Claudable, the database, other projects — blocked). It cannot read Claudable\'s data or any other project.'
      : 'This project currently runs inside Claudable\'s process. Set `PREVIEW_ISOLATION` to run it in a hardened, egress-locked container instead.');
    L.push('', '## Editing');
    L.push('The AI agent edits these files directly. Changes flow to the running preview via the shared mount — hot-reload for the frontend, rebuild-on-restart for a compiled backend. The agent has no container-runtime access; only the code it writes runs (in isolation).');
    L.push('', '## Deploy');
    L.push(isStatic
      ? '- Deploys via the project\'s **own** pipeline (its `docker-compose` + CI) — Claudable does not manage it.'
      : '- Publishes via Claudable → Gitea → Coolify.');
    L.push('');
    await fs.mkdir(path.join(projectPath, '.claudable'), { recursive: true });
    await fs.writeFile(path.join(projectPath, '.claudable', 'ARCHITECTURE.md'), L.join('\n'), 'utf8');
  } catch { /* best-effort — a doc write must never break the preview */ }
}
