/**
 * Self-hosted deploy scaffolding.
 *
 * Injects the files that make a generated site auto-deploy on push to `main`,
 * matching the New Story infra pattern (Gitea Actions host-runner +
 * docker compose + Traefik dynamic config + LetsEncrypt + wildcard DNS):
 *
 *   push main -> Gitea Actions (host runner) -> clone/pull /opt/<site>
 *             -> docker compose build & up (network_mode host)
 *             -> write Traefik route -> health check
 *
 * Result: the site is live at https://<site>.<GIT_DEPLOY_DOMAIN>.
 *
 * Files are only created if absent, so a project may customise them and the
 * customisation survives subsequent pushes.
 */

import fs from 'fs/promises';
import path from 'path';
import { getGitProviderConfig } from '@/lib/services/git-provider';
import { stackKind, type StackKind } from '@/lib/config/stacks';

export interface ScaffoldOptions {
  repoName: string;
  /** The project's stack id (templateType). Picks the production Dockerfile. */
  templateType?: string | null;
}

const DEPLOY_PORT_BASE = Number(process.env.DEPLOY_PORT_BASE || 3500);
const DEPLOY_PORT_SPAN = Number(process.env.DEPLOY_PORT_SPAN || 400); // band [3500, 3899]

// The address the reverse proxy uses to reach a host-network container. Set
// DEPLOY_HOST_GATEWAY to your proxy's view of the host (e.g. the Docker host
// gateway IP, or host.docker.internal). Kept out of the codebase so no
// deployment topology is hardcoded.
const DEPLOY_HOST_GATEWAY = process.env.DEPLOY_HOST_GATEWAY || 'host.docker.internal';

/**
 * Deterministic per-site runtime port within a configurable band, chosen to
 * avoid ports already in use on the host. Deterministic so re-runs target the
 * same port; collisions within the band surface loudly via the health check.
 */
export function deployPortFor(repoName: string): number {
  let hash = 0;
  for (let i = 0; i < repoName.length; i += 1) {
    hash = (hash * 31 + repoName.charCodeAt(i)) >>> 0;
  }
  return DEPLOY_PORT_BASE + (hash % DEPLOY_PORT_SPAN);
}

function dockerfile(stack: StackKind): string {
  // Shared prefix: install deps (lockfile or fresh) + a temporary build toolchain
  // for native addons (e.g. better-sqlite3), then build. Only the build output
  // location + how the app is served differ per framework.
  const head = `FROM node:22-alpine
WORKDIR /app

# Prefer the lockfile (reproducible) but fall back to a fresh install when it has
# drifted — agent-generated projects often edit package.json without the lock.
# Build toolchain is added temporarily so native addons compile, then removed.
COPY package*.json ./
RUN apk add --no-cache --virtual .build-deps python3 make g++ \\
 && (npm ci || npm install --no-audit --no-fund) \\
 && apk del .build-deps

COPY . .
RUN npm run build

ENV NODE_ENV=production`;

  if (stack === 'next') {
    return `# Auto-generated by Claudable. Next.js production image.
${head}
# next build -> .next/ ; \`next start\` serves it. PORT comes from compose.
CMD ["sh", "-c", "npx next start -H 0.0.0.0 -p \${PORT}"]
`;
  }

  if (stack === 'angular') {
    return `# Auto-generated by Claudable. Angular production image (static build).
${head}
# ng build -> dist/app/browser ; serve as a SPA (-s falls back to index.html).
RUN npm install -g serve
CMD ["sh", "-c", "serve -s dist/app/browser -l \${PORT}"]
`;
  }

  // nuxt (default)
  return `# Auto-generated by Claudable. Nuxt 4 production image.
${head}
# Nitro server honours PORT/HOST env vars (nuxt build -> .output/).
CMD ["node", ".output/server/index.mjs"]
`;
}

function dockerignore(): string {
  // Exclude .env so local/preview values (e.g. a dev PORT) don't get baked into
  // the image and override the compose-provided runtime config.
  return ['node_modules', '.next', '.nuxt', '.output', '.git', 'dist', 'build', 'out', '.turbo', '.vercel', '.env', '.env.*', '*.log'].join('\n') + '\n';
}

function dockerCompose(site: string, port: number): string {
  return `# Auto-generated by Claudable. Runs the site on the host network at PORT.
services:
  app:
    build: .
    container_name: ${site}
    network_mode: host          # bind directly to the host port (proxy -> host gateway:PORT)
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${port}
      - HOST=0.0.0.0
      - NITRO_PORT=${port}
      - NITRO_HOST=0.0.0.0
      - HOSTNAME=0.0.0.0
    volumes:
      # Persist app data (e.g. SQLite at ./.data) across rebuilds/redeploys.
      # Harmless for stateless apps (just an empty dir).
      - ./data:/app/.data
    # Runtime secrets from /opt/${site}/.env on the server (the deploy workflow
    # ensures the file exists; empty is fine).
    env_file:
      - .env
`;
}

function deployWorkflow(site: string, port: number, domain: string, httpBase: string, org: string): string {
  const host = `${site}.${domain}`;
  const cloneHost = httpBase.replace(/^https?:\/\//u, '');
  return `# Auto-generated by Claudable. Deploys on push to main via the host runner.
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest   # host-runner: runs on the box with docker + sudo
    steps:
      - name: Build, deploy and route ${site}
        env:
          DEPLOY_TOKEN: \${{ secrets.DEPLOY_TOKEN }}
        run: |
          set -euo pipefail
          APP=${site}
          PORT=${port}
          HOSTNAME_FQDN=${host}
          DIR=/opt/$APP
          REPO="https://oauth2:\${DEPLOY_TOKEN}@${cloneHost}/${org}/$APP.git"

          # --- Sync checkout (self-healing) -----------------------------------
          # Try to fast-forward an existing checkout; if anything is off (wrong
          # remote, detached state, corruption) fall back to a clean re-clone so
          # a deploy never gets stuck on a broken /opt dir. Preserve the runtime
          # .env (secrets) AND data/ (the persistent SQLite volume) across a
          # re-clone — both are untracked, so a clean re-clone would lose them.
          if [ -d "$DIR/.git" ] && cd "$DIR" \\
               && git remote set-url origin "$REPO" \\
               && git fetch --depth=1 origin main \\
               && git reset --hard origin/main; then
            echo "Updated existing checkout at $DIR"
          else
            echo "::warning::checkout unusable, re-cloning $DIR"
            BACKUP="/tmp/$APP.deploy-backup"
            rm -rf "$BACKUP"; mkdir -p "$BACKUP"
            [ -f "$DIR/.env" ] && cp "$DIR/.env" "$BACKUP/.env" || true
            [ -d "$DIR/data" ] && cp -a "$DIR/data" "$BACKUP/data" || true
            cd /
            sudo rm -rf "$DIR"
            sudo mkdir -p "$DIR"
            sudo chown "$(id -u):$(id -g)" "$DIR"
            git clone --depth=1 "$REPO" "$DIR"
            cd "$DIR"
            [ -f "$BACKUP/.env" ] && cp "$BACKUP/.env" "$DIR/.env" || true
            [ -d "$BACKUP/data" ] && rm -rf "$DIR/data" && cp -a "$BACKUP/data" "$DIR/data" || true
            rm -rf "$BACKUP"
          fi

          # --- Build & (re)start ----------------------------------------------
          # Ensure the runtime .env and the persistent data dir exist so the
          # compose env_file / volume mounts don't fail on a first deploy.
          touch "$DIR/.env"
          mkdir -p "$DIR/data"

          # --force-recreate guarantees the freshly-built image actually runs
          # (a plain 'up -d' keeps the old container, so new code never goes
          # live); --remove-orphans cleans up renamed/removed services.
          docker compose build
          docker compose up -d --force-recreate --remove-orphans

          # --- Reverse-proxy route (idempotent) ------------------------------
          ROUTE=/data/coolify/proxy/dynamic/$APP.yml
          sudo tee "$ROUTE" > /dev/null <<YAML
          http:
            routers:
              $APP:
                rule: "Host(\\\`$HOSTNAME_FQDN\\\`)"
                entryPoints: [https]
                service: $APP
                tls:
                  certResolver: letsencrypt
              $APP-http:
                rule: "Host(\\\`$HOSTNAME_FQDN\\\`)"
                entryPoints: [http]
                middlewares: [redirect-to-https]
                service: $APP
            services:
              $APP:
                loadBalancer:
                  servers:
                    - url: "http://${DEPLOY_HOST_GATEWAY}:$PORT"
            middlewares:
              redirect-to-https:
                redirectScheme:
                  scheme: https
                  permanent: true
          YAML

          # --- Health check (loud on failure) --------------------------------
          ok=0
          for i in $(seq 1 20); do
            if curl -fsS "http://localhost:$PORT/" > /dev/null 2>&1; then ok=1; break; fi
            sleep 3
          done
          if [ "$ok" != "1" ]; then
            echo "::error::health check failed on port $PORT"
            docker compose ps || true
            docker compose logs --tail 80 || true
            exit 1
          fi
          # Reclaim space from old image layers so the disk can't fill up.
          docker image prune -f > /dev/null 2>&1 || true
          echo "Deployed OK -> https://$HOSTNAME_FQDN (port $PORT)"
`;
}

async function writeIfAbsent(filePath: string, contents: string): Promise<void> {
  try {
    await fs.access(filePath);
    return; // already exists, keep customisations
  } catch {
    // not present -> create
  }
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, contents, 'utf8');
}

/** Always (over)write — for Claudable-managed infra files that must stay current. */
async function writeManaged(filePath: string, contents: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, contents, 'utf8');
}

/**
 * Write Dockerfile, .dockerignore, docker-compose.yml and the Gitea Actions
 * deploy workflow into the project repo (idempotent).
 */
export async function injectDeployScaffolding(repoPath: string, options: ScaffoldOptions): Promise<void> {
  const { deployDomain, httpBase, org } = getGitProviderConfig();

  // Only meaningful for the self-hosted (Gitea) flow with a deploy domain + org.
  if (!deployDomain || !org) {
    return;
  }

  const site = options.repoName.toLowerCase().replace(/[^a-z0-9-]/gu, '-').replace(/-+/gu, '-').replace(/^-|-$/gu, '');
  const port = deployPortFor(site);
  const kind = stackKind(options.templateType);

  // Dockerfile / .dockerignore / workflow are pure Claudable-managed infra:
  // overwrite them every publish so reliability fixes propagate to existing
  // repos (and the Dockerfile tracks the project's stack). docker-compose.yml is
  // written once (port stays stable; users may add env_file / extra services).
  await writeManaged(path.join(repoPath, 'Dockerfile'), dockerfile(kind));
  await writeManaged(path.join(repoPath, '.dockerignore'), dockerignore());
  await writeIfAbsent(path.join(repoPath, 'docker-compose.yml'), dockerCompose(site, port));
  await writeManaged(
    path.join(repoPath, '.gitea', 'workflows', 'deploy.yml'),
    deployWorkflow(site, port, deployDomain, httpBase, org),
  );
}
