/**
 * Self-hosted deploy scaffolding.
 *
 * Injects the files that make a generated site auto-deploy on push to `main`,
 * matching the New Story infra pattern (Gitea Actions host-runner +
 * docker compose + Traefik dynamic config + LetsEncrypt + wildcard DNS):
 *
 *   push main -> Gitea Actions (host runner) -> clone/pull /opt/<site>
 *             -> docker compose build & up (network_mode host)
 *             -> write Traefik route -> health check
 *
 * Result: the site is live at https://<site>.<GIT_DEPLOY_DOMAIN>.
 *
 * Files are only created if absent, so a project may customise them and the
 * customisation survives subsequent pushes.
 */

import fs from 'fs/promises';
import path from 'path';
import { getGitProviderConfig } from '@/lib/services/git-provider';
import { stackKind, type StackKind } from '@/lib/config/stacks';

export interface ScaffoldOptions {
  repoName: string;
  /** The project's stack id (templateType). Picks the production Dockerfile. */
  templateType?: string | null;
}

const DEPLOY_PORT_BASE = Number(process.env.DEPLOY_PORT_BASE || 3500);
const DEPLOY_PORT_SPAN = Number(process.env.DEPLOY_PORT_SPAN || 400); // band [3500, 3899]

// The address the reverse proxy uses to reach a host-network container. Set
// DEPLOY_HOST_GATEWAY to your proxy's view of the host (e.g. the Docker host
// gateway IP, or host.docker.internal). Kept out of the codebase so no
// deployment topology is hardcoded.
const DEPLOY_HOST_GATEWAY = process.env.DEPLOY_HOST_GATEWAY || 'host.docker.internal';

/**
 * Deterministic per-site runtime port within a configurable band, chosen to
 * avoid ports already in use on the host. Deterministic so re-runs target the
 * same port; collisions within the band surface loudly via the health check.
 */
function deployPortFor(repoName: string): number {
  let hash = 0;
  for (let i = 0; i < repoName.length; i += 1) {
    hash = (hash * 31 + repoName.charCodeAt(i)) >>> 0;
  }
  return DEPLOY_PORT_BASE + (hash % DEPLOY_PORT_SPAN);
}

function dockerfile(stack: StackKind): string {
  // Shared prefix: install deps (lockfile or fresh) + a temporary build toolchain
  // for native addons (e.g. better-sqlite3), then build. Only the build output
  // location + how the app is served differ per framework.
  const head = `FROM node:22-alpine
WORKDIR /app

# Prefer the lockfile (reproducible) but fall back to a fresh install when it has
# drifted — agent-generated projects often edit package.json without the lock.
# Build toolchain is added temporarily so native addons compile, then removed.
COPY package*.json ./
RUN apk add --no-cache --virtual .build-deps python3 make g++ \\
 && (npm ci || npm install --no-audit --no-fund) \\
 && apk del .build-deps

COPY . .
RUN npm run build

ENV NODE_ENV=production`;

  if (stack === 'next') {
    return `# Auto-generated by Claudable. Next.js production image.
${head}
# next build -> .next/ ; \`next start\` serves it. PORT comes from compose.
CMD ["sh", "-c", "npx next start -H 0.0.0.0 -p \${PORT}"]
`;
  }

  if (stack === 'angular') {
    return `# Auto-generated by Claudable. Angular production image (static build).
${head}
# ng build -> dist/app/browser ; serve as a SPA (-s falls back to index.html).
RUN npm install -g serve
CMD ["sh", "-c", "serve -s dist/app/browser -l \${PORT}"]
`;
  }

  // nuxt (default)
  return `# Auto-generated by Claudable. Nuxt 4 production image.
${head}
# Nitro server honours PORT/HOST env vars (nuxt build -> .output/).
CMD ["node", ".output/server/index.mjs"]
`;
}

function dockerignore(): string {
  // Exclude .env so local/preview values (e.g. a dev PORT) don't get baked into
  // the image and override the compose-provided runtime config.
  return ['node_modules', '.next', '.nuxt', '.output', '.git', 'dist', 'build', 'out', '.turbo', '.vercel', '.env', '.env.*', '*.log'].join('\n') + '\n';
}

function dockerCompose(site: string, port: number): string {
  return `# Auto-generated by Claudable. Runs the site on the host network at PORT.
services:
  app:
    build: .
    container_name: ${site}
    network_mode: host          # bind directly to the host port (proxy -> host gateway:PORT)
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${port}
      - HOST=0.0.0.0
      - NITRO_PORT=${port}
      - NITRO_HOST=0.0.0.0
      - HOSTNAME=0.0.0.0
    volumes:
      # Persist app data (e.g. SQLite at ./.data) across rebuilds/redeploys.
      # Harmless for stateless apps (just an empty dir).
      - ./data:/app/.data
    # Runtime secrets from /opt/${site}/.env on the server (the deploy workflow
    # ensures the file exists; empty is fine).
    env_file:
      - .env
`;
}

function deployWorkflow(site: string, port: number, domain: string, httpBase: string, org: string): string {
  const host = `${site}.${domain}`;
  const cloneHost = httpBase.replace(/^https?:\/\//u, '');
  return `# Auto-generated by Claudable. Deploys on push to main via the host runner.
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest   # host-runner: runs on the box with docker + sudo
    steps:
      - name: Build, deploy and route ${site}
        env:
          DEPLOY_TOKEN: \${{ secrets.DEPLOY_TOKEN }}
          DATABASE_URL: \${{ secrets.DATABASE_URL }}
        run: |
          set -euo pipefail
          APP=${site}
          PORT=${port}
          HOSTNAME_FQDN=${host}
          DIR=/opt/$APP
          REPO="https://oauth2:\${DEPLOY_TOKEN}@${cloneHost}/${org}/$APP.git"

          # --- Sync checkout (self-healing) -----------------------------------
          # Try to fast-forward an existing checkout; if anything is off (wrong
          # remote, detached state, corruption) fall back to a clean re-clone so
          # a deploy never gets stuck on a broken /opt dir. Preserve the runtime
          # .env (secrets) AND data/ (the persistent SQLite volume) across a
          # re-clone — both are untracked, so a clean re-clone would lose them.
          if [ -d "$DIR/.git" ] && cd "$DIR" \\
               && git remote set-url origin "$REPO" \\
               && git fetch --depth=1 origin main \\
               && git reset --hard origin/main; then
            echo "Updated existing checkout at $DIR"
          else
            echo "::warning::checkout unusable, re-cloning $DIR"
            BACKUP="/tmp/$APP.deploy-backup"
            rm -rf "$BACKUP"; mkdir -p "$BACKUP"
            [ -f "$DIR/.env" ] && cp "$DIR/.env" "$BACKUP/.env" || true
            [ -d "$DIR/data" ] && cp -a "$DIR/data" "$BACKUP/data" || true
            cd /
            sudo rm -rf "$DIR"
            sudo mkdir -p "$DIR"
            sudo chown "$(id -u):$(id -g)" "$DIR"
            git clone --depth=1 "$REPO" "$DIR"
            cd "$DIR"
            [ -f "$BACKUP/.env" ] && cp "$BACKUP/.env" "$DIR/.env" || true
            [ -d "$BACKUP/data" ] && rm -rf "$DIR/data" && cp -a "$BACKUP/data" "$DIR/data" || true
            rm -rf "$BACKUP"
          fi

          # --- Build & (re)start ----------------------------------------------
          # Ensure the runtime .env and the persistent data dir exist so the
          # compose env_file / volume mounts don't fail on a first deploy.
          touch "$DIR/.env"
          mkdir -p "$DIR/data"

          # Inject the managed DATABASE_URL (from the repo secret) into the runtime
          # .env so a Claudable-provisioned Postgres is available to the deployed app.
          if [ -n "\${DATABASE_URL:-}" ]; then
            grep -v '^DATABASE_URL=' "$DIR/.env" > "$DIR/.env.next" 2>/dev/null || true
            echo "DATABASE_URL=$DATABASE_URL" >> "$DIR/.env.next"
            mv "$DIR/.env.next" "$DIR/.env"
          fi

          # --force-recreate guarantees the freshly-built image actually runs
          # (a plain 'up -d' keeps the old container, so new code never goes
          # live); --remove-orphans cleans up renamed/removed services.
          docker compose build
          docker compose up -d --force-recreate --remove-orphans

          # --- Reverse-proxy route (idempotent) ------------------------------
          ROUTE=/data/coolify/proxy/dynamic/$APP.yml
          sudo tee "$ROUTE" > /dev/null <<YAML
          http:
            routers:
              $APP:
                rule: "Host(\\\`$HOSTNAME_FQDN\\\`)"
                entryPoints: [https]
                service: $APP
                tls:
                  certResolver: letsencrypt
              $APP-http:
                rule: "Host(\\\`$HOSTNAME_FQDN\\\`)"
                entryPoints: [http]
                middlewares: [redirect-to-https]
                service: $APP
            services:
              $APP:
                loadBalancer:
                  servers:
                    - url: "http://${DEPLOY_HOST_GATEWAY}:$PORT"
            middlewares:
              redirect-to-https:
                redirectScheme:
                  scheme: https
                  permanent: true
          YAML

          # --- Health check (loud on failure) --------------------------------
          ok=0
          for i in $(seq 1 20); do
            if curl -fsS "http://localhost:$PORT/" > /dev/null 2>&1; then ok=1; break; fi
            sleep 3
          done
          if [ "$ok" != "1" ]; then
            echo "::error::health check failed on port $PORT"
            docker compose ps || true
            docker compose logs --tail 80 || true
            exit 1
          fi
          # Reclaim space from old image layers so the disk can't fill up.
          docker image prune -f > /dev/null 2>&1 || true
          echo "Deployed OK -> https://$HOSTNAME_FQDN (port $PORT)"
`;
}

/**
 * Production compose for a Filament (Laravel) golden-template project. Unlike
 * the node stacks, the app image is the TEMPLATE's own multi-stage
 * build/service/Dockerfile (php-fpm + nginx + supervisor, target `final`) — it
 * bakes in composer --no-dev + the vite build and runs entry.sh (renders .env
 * from the `secrets` JSON, migrates, caches, serves). Postgres runs in a sidecar
 * on the private compose network; the app reaches it as host `db`.
 */
function dockerComposeLaravel(site: string, port: number): string {
  return `# Auto-generated by Claudable. Filament (Laravel) production stack.
name: ${site}
services:
  app:
    container_name: ${site}
    build:
      context: .
      dockerfile: ./build/service/Dockerfile
      target: final
    environment:
      # The deploy workflow exports the secrets JSON before 'compose up'; entry.sh
      # reads $secrets and renders .env from it (keeps the JSON out of compose
      # variable interpolation so special characters survive).
      - secrets
    ports:
      - "${port}:80"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    container_name: ${site}-db
    image: postgres:17.7-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: sa
      # Interpolated from the deploy workflow's shell env (same generated value
      # that goes into secrets.json's DB_PASSWORD), so the credential is never
      # committed. The DB has no published port (private compose net only).
      POSTGRES_PASSWORD: "\${DB_PASSWORD:?DB_PASSWORD must be exported by the deploy workflow}"
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d app"]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped
`;
}

/**
 * Deploy workflow for a Filament (Laravel) project. Same self-healing host-runner
 * skeleton as the node one, but generates + persists a runtime `secrets.json`
 * (APP_KEY, DB pointing at the compose Postgres sidecar, preview-safe FILESYSTEM/
 * MAIL/DBSYNC) and exports it as `$secrets` for entry.sh. entry.sh migrates on
 * every boot, so there is no separate migrate step. AWS App Runner workflows the
 * template ships under .github/ are removed at publish time (see injector).
 */
function deployWorkflowLaravel(site: string, port: number, domain: string, httpBase: string, org: string): string {
  const host = `${site}.${domain}`;
  const cloneHost = httpBase.replace(/^https?:\/\//u, '');
  return `# Auto-generated by Claudable. Filament (Laravel) deploy via the host runner.
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest   # host-runner: runs on the box with docker + sudo
    steps:
      - name: Build, deploy and route ${site}
        env:
          DEPLOY_TOKEN: \${{ secrets.DEPLOY_TOKEN }}
        run: |
          set -euo pipefail
          APP=${site}
          PORT=${port}
          HOSTNAME_FQDN=${host}
          DIR=/opt/$APP
          REPO="https://oauth2:\${DEPLOY_TOKEN}@${cloneHost}/${org}/$APP.git"

          # --- Sync checkout (self-healing) -----------------------------------
          # Preserve secrets.json (generated once) AND data/ (the persistent
          # Postgres volume) across a re-clone — both are untracked.
          if [ -d "$DIR/.git" ] && cd "$DIR" \\
               && git remote set-url origin "$REPO" \\
               && git fetch --depth=1 origin main \\
               && git reset --hard origin/main; then
            echo "Updated existing checkout at $DIR"
          else
            echo "::warning::checkout unusable, re-cloning $DIR"
            BACKUP="/tmp/$APP.deploy-backup"
            rm -rf "$BACKUP"; mkdir -p "$BACKUP"
            [ -f "$DIR/secrets.json" ] && cp "$DIR/secrets.json" "$BACKUP/secrets.json" || true
            [ -d "$DIR/data" ] && cp -a "$DIR/data" "$BACKUP/data" || true
            cd /
            sudo rm -rf "$DIR"
            sudo mkdir -p "$DIR"
            sudo chown "$(id -u):$(id -g)" "$DIR"
            git clone --depth=1 "$REPO" "$DIR"
            cd "$DIR"
            [ -f "$BACKUP/secrets.json" ] && cp "$BACKUP/secrets.json" "$DIR/secrets.json" || true
            [ -d "$BACKUP/data" ] && rm -rf "$DIR/data" && cp -a "$BACKUP/data" "$DIR/data" || true
            rm -rf "$BACKUP"
          fi

          # --- Runtime secrets (generated once, persisted across deploys) -----
          mkdir -p "$DIR/data"
          if [ ! -f "$DIR/secrets.json" ]; then
            echo "Generating $DIR/secrets.json (first deploy)"
            APP_KEY="base64:$(openssl rand -base64 32)"
            DB_PASS="$(openssl rand -hex 24)"
            cat > "$DIR/secrets.json" <<JSON
          {
            "APP_NAME": "${site}",
            "APP_ENV": "production",
            "APP_KEY": "$APP_KEY",
            "APP_DEBUG": "false",
            "APP_URL": "https://$HOSTNAME_FQDN",
            "LOG_CHANNEL": "stack",
            "LOG_LEVEL": "error",
            "DB_CONNECTION": "pgsql",
            "DB_HOST": "db",
            "DB_PORT": "5432",
            "DB_DATABASE": "app",
            "DB_USERNAME": "sa",
            "DB_PASSWORD": "$DB_PASS",
            "CACHE_DRIVER": "file",
            "SESSION_DRIVER": "database",
            "SESSION_LIFETIME": "120",
            "QUEUE_CONNECTION": "database",
            "FILESYSTEM_DISK": "public",
            "MEDIA_DISK": "public",
            "MAIL_MAILER": "log",
            "MAIL_FROM_ADDRESS": "noreply@$HOSTNAME_FQDN",
            "MAIL_FROM_NAME": "${site}",
            "DBSYNC_ENABLED": "false"
          }
          JSON
          fi
          export secrets="$(cat "$DIR/secrets.json")"
          # Feed the same DB password to the Postgres sidecar (compose interpolates
          # POSTGRES_PASSWORD from this) so app + db agree without committing it.
          export DB_PASSWORD="$(grep -oP '"DB_PASSWORD":\\s*"\\K[^"]+' "$DIR/secrets.json")"

          # --- Build & (re)start ----------------------------------------------
          docker compose build
          docker compose up -d --force-recreate --remove-orphans

          # --- Reverse-proxy route (idempotent) ------------------------------
          ROUTE=/data/coolify/proxy/dynamic/$APP.yml
          sudo tee "$ROUTE" > /dev/null <<YAML
          http:
            routers:
              $APP:
                rule: "Host(\\\`$HOSTNAME_FQDN\\\`)"
                entryPoints: [https]
                service: $APP
                tls:
                  certResolver: letsencrypt
              $APP-http:
                rule: "Host(\\\`$HOSTNAME_FQDN\\\`)"
                entryPoints: [http]
                middlewares: [redirect-to-https]
                service: $APP
            services:
              $APP:
                loadBalancer:
                  servers:
                    - url: "http://${DEPLOY_HOST_GATEWAY}:$PORT"
            middlewares:
              redirect-to-https:
                redirectScheme:
                  scheme: https
                  permanent: true
          YAML

          # --- Health check (loud on failure) --------------------------------
          # entry.sh migrates + caches before nginx binds, so allow time.
          ok=0
          for i in $(seq 1 40); do
            if curl -fsS "http://localhost:$PORT/up" > /dev/null 2>&1 \\
               || curl -fsS "http://localhost:$PORT/" > /dev/null 2>&1; then ok=1; break; fi
            sleep 3
          done
          if [ "$ok" != "1" ]; then
            echo "::error::health check failed on port $PORT"
            docker compose ps || true
            docker compose logs --tail 120 || true
            exit 1
          fi
          docker image prune -f > /dev/null 2>&1 || true
          echo "Deployed OK -> https://$HOSTNAME_FQDN (port $PORT)"
`;
}

async function writeIfAbsent(filePath: string, contents: string): Promise<void> {
  try {
    await fs.access(filePath);
    return; // already exists, keep customisations
  } catch {
    // not present -> create
  }
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, contents, 'utf8');
}

/** Always (over)write — for Claudable-managed infra files that must stay current. */
async function writeManaged(filePath: string, contents: string): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, contents, 'utf8');
}

/**
 * Remove every CI workflow file except the Claudable-managed deploy.yml. The
 * privileged host-runner executes anything under .gitea/workflows and
 * .github/workflows, and the agent can write those paths — so a foreign workflow
 * is root RCE on the deploy box. Only call for Claudable-scaffolded projects.
 */
async function stripForeignWorkflows(repoPath: string): Promise<void> {
  await fs.rm(path.join(repoPath, '.github', 'workflows'), { recursive: true, force: true }).catch(() => {});
  const giteaWf = path.join(repoPath, '.gitea', 'workflows');
  try {
    for (const f of await fs.readdir(giteaWf)) {
      if (f !== 'deploy.yml') {
        await fs.rm(path.join(giteaWf, f), { recursive: true, force: true }).catch(() => {});
      }
    }
  } catch { /* no workflows dir */ }
}

/**
 * Write Dockerfile, .dockerignore, docker-compose.yml and the Gitea Actions
 * deploy workflow into the project repo (idempotent).
 */
export async function injectDeployScaffolding(repoPath: string, options: ScaffoldOptions): Promise<void> {
  const { deployDomain, httpBase, org } = getGitProviderConfig();

  // Only meaningful for the self-hosted (Gitea) flow with a deploy domain + org.
  if (!deployDomain || !org) {
    return;
  }

  // Respect projects that manage their own build/deploy. An imported project
  // defines how it runs via `.claudable/preview.json` and ships its OWN
  // Dockerfile(s) + Gitea Actions workflows. Overwriting its Dockerfile and
  // `.gitea/workflows/deploy.yml` here would clobber a working CI/CD pipeline
  // (e.g. StoryLoop's Gitea Actions). Only projects Claudable scaffolded itself
  // (no preview.json) get Claudable-managed deploy infra.
  try {
    await fs.access(path.join(repoPath, '.claudable', 'preview.json'));
    return; // imported / self-managed — leave its deploy files untouched
  } catch { /* no preview.json → a Claudable-scaffolded project; proceed */ }
  // SECURITY: the deploy host-runner executes EVERY workflow file in the repo
  // with docker + sudo (root on the box). The agent controls the whole project
  // tree, so an agent-authored workflow would be arbitrary ROOT code on the next
  // push. Claudable manages exactly one workflow (.gitea/workflows/deploy.yml);
  // strip every other workflow file (and all of .github/workflows) at publish.
  // Imported/self-managed projects (preview.json) returned above, so their own
  // CI is left untouched — this only affects Claudable-scaffolded projects.
  await stripForeignWorkflows(repoPath);

  const site = options.repoName.toLowerCase().replace(/[^a-z0-9-]/gu, '-').replace(/-+/gu, '-').replace(/^-|-$/gu, '');
  const port = deployPortFor(site);
  const kind = stackKind(options.templateType);

  if (kind === 'laravel') {
    // The Filament golden template ships its OWN production build/service/Dockerfile
    // (php-fpm + nginx) and a correct .dockerignore — do NOT overwrite them with the
    // node image. Provide only the compose (app builds from the template Dockerfile +
    // a Postgres sidecar) and the Laravel deploy workflow. (The template's AWS App
    // Runner workflows under .github/ were already removed by stripForeignWorkflows.)
    await writeIfAbsent(path.join(repoPath, 'docker-compose.yml'), dockerComposeLaravel(site, port));
    await writeManaged(
      path.join(repoPath, '.gitea', 'workflows', 'deploy.yml'),
      deployWorkflowLaravel(site, port, deployDomain, httpBase, org),
    );
    return;
  }

  // Dockerfile / .dockerignore / workflow are pure Claudable-managed infra:
  // overwrite them every publish so reliability fixes propagate to existing
  // repos (and the Dockerfile tracks the project's stack). docker-compose.yml is
  // written once (port stays stable; users may add env_file / extra services).
  await writeManaged(path.join(repoPath, 'Dockerfile'), dockerfile(kind));
  await writeManaged(path.join(repoPath, '.dockerignore'), dockerignore());
  await writeIfAbsent(path.join(repoPath, 'docker-compose.yml'), dockerCompose(site, port));
  await writeManaged(
    path.join(repoPath, '.gitea', 'workflows', 'deploy.yml'),
    deployWorkflow(site, port, deployDomain, httpBase, org),
  );
}
