/**
 * Self-hosted deploy scaffolding.
 *
 * Injects the files that make a generated site auto-deploy on push to `main`,
 * matching the New Story infra pattern (Gitea Actions host-runner +
 * docker compose + Traefik dynamic config + LetsEncrypt + wildcard DNS):
 *
 *   push main -> Gitea Actions (host runner) -> clone/pull /opt/<site>
 *             -> docker compose build & up (network_mode host)
 *             -> write Traefik route -> health check
 *
 * Result: the site is live at https://<site>.<GIT_DEPLOY_DOMAIN>.
 *
 * Files are only created if absent, so a project may customise them and the
 * customisation survives subsequent pushes.
 */

import fs from 'fs/promises';
import path from 'path';
import { getGitProviderConfig } from '@/lib/services/git-provider';

export interface ScaffoldOptions {
  repoName: string;
}

const DEPLOY_PORT_BASE = Number(process.env.DEPLOY_PORT_BASE || 3500);
const DEPLOY_PORT_SPAN = Number(process.env.DEPLOY_PORT_SPAN || 400); // band [3500, 3899]

/**
 * Deterministic per-site runtime port in a band that avoids the ports already
 * in use on the box (3000-3009, 3100, 3333/3334/3340/3400, 4000, 8080, ...).
 * Deterministic so re-runs target the same port; collisions within the band
 * are unlikely and surface loudly via the health check.
 */
export function deployPortFor(repoName: string): number {
  let hash = 0;
  for (let i = 0; i < repoName.length; i += 1) {
    hash = (hash * 31 + repoName.charCodeAt(i)) >>> 0;
  }
  return DEPLOY_PORT_BASE + (hash % DEPLOY_PORT_SPAN);
}

function dockerfile(): string {
  return `# Auto-generated by Claudable. Generic Nuxt 4 production image.
FROM node:22-alpine
WORKDIR /app

# Install dependencies (use lockfile when present)
COPY package*.json ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi

# Build (nuxt build -> .output/)
COPY . .
RUN npm run build

ENV NODE_ENV=production
# Nitro server honours PORT/HOST env vars
CMD ["node", ".output/server/index.mjs"]
`;
}

function dockerignore(): string {
  return ['node_modules', '.next', '.nuxt', '.output', '.git', 'dist', 'build', 'out', '.turbo', '.vercel', '*.log'].join('\n') + '\n';
}

function dockerCompose(site: string, port: number): string {
  return `# Auto-generated by Claudable. Runs the site on the host network at PORT.
services:
  app:
    build: .
    container_name: ${site}
    network_mode: host          # bind directly to the host port (Traefik -> 10.0.1.1:PORT)
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${port}
      - HOST=0.0.0.0
      - NITRO_PORT=${port}
      - NITRO_HOST=0.0.0.0
      - HOSTNAME=0.0.0.0
    # Uncomment to load secrets from /opt/${site}/.env on the server:
    # env_file:
    #   - .env
`;
}

function deployWorkflow(site: string, port: number, domain: string, httpBase: string, org: string): string {
  const host = `${site}.${domain}`;
  const cloneHost = httpBase.replace(/^https?:\/\//u, '');
  return `# Auto-generated by Claudable. Deploys on push to main via the host runner.
name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest   # host-runner: runs on the box with docker + sudo
    steps:
      - name: Build, deploy and route ${site}
        env:
          DEPLOY_TOKEN: \${{ secrets.DEPLOY_TOKEN }}
        run: |
          set -euo pipefail
          APP=${site}
          PORT=${port}
          HOSTNAME_FQDN=${host}
          DIR=/opt/$APP
          REPO="https://oauth2:\${DEPLOY_TOKEN}@${cloneHost}/${org}/$APP.git"

          # First deploy clones; later deploys fast-forward.
          if [ ! -d "$DIR/.git" ]; then
            sudo mkdir -p "$DIR"
            sudo chown "$(id -u):$(id -g)" "$DIR"
            git clone "$REPO" "$DIR"
          fi
          cd "$DIR"
          git remote set-url origin "$REPO"
          git fetch origin main
          git reset --hard origin/main

          # Build & (re)start the container (cached; rebuilds changed layers)
          docker compose build
          docker compose up -d

          # Traefik route (idempotent): host gateway is 10.0.1.1 on this box
          ROUTE=/data/coolify/proxy/dynamic/$APP.yml
          sudo tee "$ROUTE" > /dev/null <<YAML
          http:
            routers:
              $APP:
                rule: "Host(\\\`$HOSTNAME_FQDN\\\`)"
                entryPoints: [https]
                service: $APP
                tls:
                  certResolver: letsencrypt
              $APP-http:
                rule: "Host(\\\`$HOSTNAME_FQDN\\\`)"
                entryPoints: [http]
                middlewares: [redirect-to-https]
                service: $APP
            services:
              $APP:
                loadBalancer:
                  servers:
                    - url: "http://10.0.1.1:$PORT"
            middlewares:
              redirect-to-https:
                redirectScheme:
                  scheme: https
                  permanent: true
          YAML

          # Health check
          sleep 10
          curl -sf "http://localhost:$PORT/" > /dev/null && echo "Deploy OK -> https://$HOSTNAME_FQDN"
`;
}

async function writeIfAbsent(filePath: string, contents: string): Promise<void> {
  try {
    await fs.access(filePath);
    return; // already exists, keep customisations
  } catch {
    // not present -> create
  }
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, contents, 'utf8');
}

/**
 * Write Dockerfile, .dockerignore, docker-compose.yml and the Gitea Actions
 * deploy workflow into the project repo (idempotent).
 */
export async function injectDeployScaffolding(repoPath: string, options: ScaffoldOptions): Promise<void> {
  const { deployDomain, httpBase, org } = getGitProviderConfig();

  // Only meaningful for the self-hosted (Gitea) flow with a deploy domain + org.
  if (!deployDomain || !org) {
    return;
  }

  const site = options.repoName.toLowerCase().replace(/[^a-z0-9-]/gu, '-').replace(/-+/gu, '-').replace(/^-|-$/gu, '');
  const port = deployPortFor(site);

  await writeIfAbsent(path.join(repoPath, 'Dockerfile'), dockerfile());
  await writeIfAbsent(path.join(repoPath, '.dockerignore'), dockerignore());
  await writeIfAbsent(path.join(repoPath, 'docker-compose.yml'), dockerCompose(site, port));
  await writeIfAbsent(
    path.join(repoPath, '.gitea', 'workflows', 'deploy.yml'),
    deployWorkflow(site, port, deployDomain, httpBase, org),
  );
}
